# Generated by Django 5.2.1 on 2025-06-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="mercado_pago_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="status_pagamento",
            field=models.CharField(default="pendente", max_length=20),
        ),
    ]
