# Generated by Django 4.2.20 on 2025-05-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_pedido_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
