# Generated by Django 4.2.20 on 2025-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_carrinho"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_user",
            name="otp_ativo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="create_user",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
