# Generated by Django 4.2.20 on 2025-05-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_create_user_otp_ativo_create_user_otp_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="create_user",
            name="otp_ativo",
        ),
        migrations.RemoveField(
            model_name="create_user",
            name="otp_secret",
        ),
    ]
