# Generated by Django 4.2.20 on 2025-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_remove_create_user_otp_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_user",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="create_user",
            name="mfa_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
