# Generated by Django 4.2.20 on 2025-06-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0009_create_user_mfa_enabled_create_user_mfa_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="create_user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
