# Generated by Django 4.2.20 on 2025-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0010_create_user_is_active_create_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_user",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
