# Generated by Django 5.2.1 on 2025-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0011_create_user_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=25)),
                ("numero", models.CharField(max_length=5)),
                ("complemento", models.CharField(max_length=25)),
                ("cep", models.CharField(max_length=8)),
            ],
        ),
    ]
