# Generated by Django 5.2.1 on 2025-06-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0013_endereco_userendereco_alter_endereco_bairro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="userEndereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
